name: HyperCells
version: "0.9.1-beta"
license: "CC BY-SA 4.0"
date: 2024-03-05
description: |
    A GAP package for constructing primitive cells and supercells of hyperbolic lattices

authors:
    - name: Patrick M. Lenggenhager
      url: https://patrick-lenggenhager.github.io
    - name: Joseph Maciejko
      url: mailto:maciejko@ualberta.ca
    - name: Tom치코 Bzdu코ek
      url: mailto:tomas.bzdusek@uzh.ch

maintainers:
    - name: Patrick M. Lenggenhager
      url: https://patrick-lenggenhager.github.io

GAP: ">= 4.11"

www: https://patrick-lenggenhager.github.io/HyperCells/
readme: README.md
packageinfo: https://patrick-lenggenhager.github.io/HyperCells/PackageInfo.g
github: https://github.com/patrick-lenggenhager/HyperCells

downloads:
    - name: .tar.gz
      url: https://github.com/patrick-lenggenhager/HyperCells/releases/download/v0.9.1-beta/HyperCells-0.9.1-beta.tar.gz

abstract: |

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    hyperbolic lattices, triangle groups.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>LMB24</span>]   <b class='BibAuthor'>Lenggenhager, P. M., Maciejko, J. and Bzdu코ek, T.</b>,
     <i class='BibTitle'>HyperCells, A GAP package for constructing primitive cells and supercells of hyperbolic lattices,
             Version 0.9.1-beta</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://patrick-lenggenhager.github.io/HyperCells/">https://patrick-lenggenhager.github.io/HyperCells/</a></span>.
    </p>
    

bibtex: |
    @misc{ HyperCells0.9.1-beta,
      author =           {Lenggenhager, P. M. and Maciejko, J. and Bzdu{\v s}ek, T.},
      title =            {{HyperCells}, A GAP package for constructing primitive cells and supercells of hyperbolic lattices, {V}ersion 0.9.1-beta},
      month =            {Mar},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href {https://patrick-lenggenhager.github.io/HyperCells/} {\texttt{https://patrick-lenggenhager.github.io/}\discretionary {}{}{}\texttt{HyperCells/}}},
      keywords =         {hyperbolic lattices; triangle groups},
      printedkey =       {LMB24}
    }

