name: HyperCells
version: "1.0.0"
license: "CC BY-SA 4.0"
date: 2024-12-03
description: |
    A GAP package for constructing primitive cells and supercells of hyperbolic lattices

authors:
    - name: Patrick M. Lenggenhager
      url: https://patrick-lenggenhager.github.io
    - name: Joseph Maciejko
      url: mailto:maciejko@ualberta.ca
    - name: Tom치코 Bzdu코ek
      url: mailto:tomas.bzdusek@uzh.ch

maintainers:
    - name: Patrick M. Lenggenhager
      url: https://patrick-lenggenhager.github.io

GAP: ">= 4.11"

suggested-pkgs:
    - name: "kbmag"
      version: ">= 1.5.10"
      url: "https://gap-packages.github.io/kbmag"

www: https://HyperCells.github.io/HyperCells/
readme: README.md
packageinfo: https://HyperCells.github.io/HyperCells/PackageInfo.g
github: https://github.com/HyperCells/HyperCells

downloads:
    - name: .tar.gz
      url: https://github.com/HyperCells/HyperCells/releases/download/v1.0.0/HyperCells-1.0.0.tar.gz

abstract: |

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    hyperbolic lattices, triangle groups.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>LMB24</span>]   <b class='BibAuthor'>Lenggenhager, P. M., Maciejko, J. and Bzdu코ek, T.</b>,
     <i class='BibTitle'>HyperCells, A GAP package for constructing primitive cells and supercells of hyperbolic lattices,
             Version 1.0.0</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://HyperCells.github.io/HyperCells/">https://HyperCells.github.io/HyperCells/</a></span>.
    </p>
    

bibtex: |
    @misc{ HyperCells1.0.0,
      author =           {Lenggenhager, P. M. and Maciejko, J. and Bzdu{\v s}ek, T.},
      title =            {{HyperCells}, A GAP package for constructing primitive cells and supercells of hyperbolic lattices, {V}ersion 1.0.0},
      month =            {Dec},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href {https://HyperCells.github.io/HyperCells/} {\texttt{https://HyperCells.github.io/}\discretionary {}{}{}\texttt{HyperCells/}}},
      keywords =         {hyperbolic lattices; triangle groups},
      printedkey =       {LMB24}
    }

