name: HyperCells
version: "0.9.0"
license: "CC BY-SA 4.0"
date: 2023-11-27
description: |
    A GAP package for constructing primitive cells and supercells of hyperbolic lattices

authors:
    - name: Patrick M. Lenggenhager
      url: https://patrick-lenggenhager.github.io
    - name: Joseph Maciejko
      url: mailto:maciejko@ualberta.ca
    - name: Tom치코 Bzdu코ek
      url: mailto:tomas.bzdusek@uzh.ch

maintainers:
    - name: Patrick M. Lenggenhager
      url: https://patrick-lenggenhager.github.io

GAP: ">= 4.11"

www: https://patrick-lenggenhager.github.io/HyperCells/
readme: README.md
packageinfo: https://patrick-lenggenhager.github.io/HyperCells/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/patrick-lenggenhager/HyperCells/releases/download/v0.9.0/HyperCells-0.9.0.tar.gz

abstract: |

status: dev
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
keywords: |
    hyperbolic lattices, triangle groups.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>LMB23</span>]   <b class='BibAuthor'>Lenggenhager, P. M., Maciejko, J. and Bzdu코ek, T.</b>,
     <i class='BibTitle'>HyperCells, A GAP package for constructing primitive cells and supercells of hyperbolic lattices,
             Version 0.9.0</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://patrick-lenggenhager.github.io/HyperCells/">https://patrick-lenggenhager.github.io/HyperCells/</a></span>.
    </p>
    

bibtex: |
    @misc{ HyperCells0.9.0,
      author =           {Lenggenhager, P. M. and Maciejko, J. and Bzdu{\v s}ek, T.},
      title =            {{HyperCells}, A GAP package for constructing primitive cells and supercells of hyperbolic lattices, {V}ersion 0.9.0},
      month =            {Nov},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href {https://patrick-lenggenhager.github.io/HyperCells/} {\texttt{https://patrick-lenggenhager.github.io/}\discretionary {}{}{}\texttt{HyperCells/}}},
      keywords =         {hyperbolic lattices; triangle groups},
      printedkey =       {LMB23}
    }

